config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "events#index"
  resources :users, only: [:show, :edit, :update]
  resources :rooms, only: [:index, :create, :show]
  resources :messages, only: [:create, :destroy]


  resources :events, only: [:index, :show, :new, :create, :destroy] do
    resources :comments, only: [:create, :destroy]
    resource :entries, only: [:create]
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :image, ImageUploader
  
  #イベント関連
  has_many :events, dependent: :destroy
  has_many :recruiting_events, class_name: 'Event', foreign_key: "recruiter_id"
  has_many :applicant_events, class_name: 'Event', foreign_key: "applicant_id"

  #エントリー関連
  has_many :entries, dependent: :destroy
  has_many :entry_events, through: :entries, source: :event

  #DM機能関連
  has_many :messages
  has_many :deals
  has_many :rooms, through: :deals

  
  has_many :comments, dependent: :destroy
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]

  def show
    @events = @user.events
    @entry_events = @user.entry_events # 追加
    #DM機能
    @currentUserDeal = Deal.where(user_id: current_user.id)
    @userDeal = Deal.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserDeal.each do |cu|
        @userDeal.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @deal = Deal.new
      end
    end
  end

  def edit
  end

  def update
    @user.update(user_params)
  end

  private
  def user_params
    params.require(:user).permit(:name, :genre, :introduction, :email, :password, :password_confirmation, :image )
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/edit.html.haml
.Adjust
  .Adjust--FormBox
    %section.EditHeading
      %h1.title
        Profile Edit
    %section.UserDetails__field
      = form_with(model: @user, local: true, class: :EditForm) do |f|

        .UserImage 
          - if @user.image?
            = f.label :image, class: 'UserImage__icon' do
              = image_tag @user.image.url, class: "UserImage__icon "
              -# = icon("fa", "image", class: "TouchHere")
              = f.file_field :image, class: 'Hidden'

          - else
            = f.label :image, class: 'UserImage__default' do
              = image_tag asset_path 'No-image.png', class: "NoImage__icon"
              = f.file_field :image, class: 'Hidden'
        
        .UserNameEdit
          %p 名前：
          = f.label class: 'Username' do
            = f.text_field :name, placeholder: "name", class: "text_field"
              
        
        .UserEmailEdit
          %p メールアドレス：
          = f.label class: 'Useremail' do
            = f.text_field :email, placeholder: "email", class: "text_field"

        .UserSkillEdit
          %p 特技：
          = f.label class: 'Userskill' do
            = f.text_field :genre, placeholder: "skill", class: "text_field"
        
        .UserIntroductionEdit
          %p 自己紹介文：
          = f.label class: 'Userintroduction' do
            = f.text_area :introduction, placeholder: "紹介文", class: "text_area"
        
        .SubmitArea
          = f.submit 'プロフィールを更新', class: 'SubmitArea__btn' 
-# .EditBox
-#   .EditBox--image

app/views/users/show.html.haml
.ContentMypage
  .MypageTop
    .MypageImage
      - if @user.image?
        = image_tag @user.image.url, class: "UserImage__icon"
      - else
        = image_tag asset_path("No-image.png"), class: "NoImage__icon"
    .MypageName
      = @user.name

  .MypageMiddle 
    %h1 About Me
    %table.ShowTable
      %tr
        %th 名前
        %td.name 
          = @user.name
      %tr
        %th メールアドレス
        %td.email
          = @user.email
      %tr
        %th パフォーマンススキル
        %td.genre
          = @user.genre
      %tr
        %th 自己紹介
        %td.introduction
          = @user.introduction
    - if user_signed_in? && current_user.id == @user.id
      = link_to "プロフィール編集", edit_user_path(@user.id), method: :get, class: "edit"

  .ApplicatedEventName 申し込み済みのイベント一覧

  .ApplicatedEvent
    - @entry_events.each do |event| #自分が申し込んだイベントの情報を表示
      .Overview
        .Overview--name
          = event.eventname
        .Overview--image
          = image_tag event.images.first.image.url

  .To-ChatRoom
    - unless @user.id == current_user.id
      - if @isRoom == true
        %p.user-show-room
          %a.btn.btn-primary.btn-lg{:href => "/rooms/#{@roomId}"} メッセージを送る
      - else
        = form_for @room do |f|
          = fields_for @deal do |e|
            = e.hidden_field :user_id, value: @user.id
          = f.submit "メッセージを送る", class:"btn btn-primary btn-lg user-show-chat"
      

app/views/users/update.html.haml
.ContentUpdate
  .success
    %h3 更新が完了しました。
    = link_to "マイページに戻る", user_path(current_user), class: "UpdatedUser"