config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "events#index"
  resources :users, only: [:show, :edit, :update]
  resources :rooms, only: [:index, :create, :show]
  resources :messages, only: [:create, :destroy]


  resources :events, only: [:index, :show, :new, :create, :destroy] do
    resources :comments, only: [:create, :destroy]
    resource :entries, only: [:create]
  end
  
end

app/views/modules/_footer.html.haml
%footer
  %h1 さあ、もう一度、舞台に立ってみませんか。
  %p &copy; 2020 Unity

app/views/modules/_header.html.haml
%header
  .container
    .header-left
      %img.logo{:src => "https://dancemaster.avex.jp/academy/genre/images/t_hiphop.png"}
    .header-center
      %ul
        %li
          = link_to "トップページ", events_path, method: :get, class: "btn"
        -# %li 
        -#   = link_to "Unityとは", "#", method: :get, class: "btn"
        %li 
          = link_to "取引一覧", rooms_path, method: :get, class: "btn"
    .header-right
      - if user_signed_in?
        %ul
          %li
            = link_to "マイページ", "/users/#{current_user.id}", class: 'ToMypage'
          %li
            = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'Logout'
        -# - if @user.image?
        -#   = image_tag @user.image.url, class: "user-circle"
        -# - else
        -#   = icon('far', 'smile-wink', class: "user-circle" )
      - else
        %ul
          %li
            = link_to "ログイン", new_user_session_path, class: "post"
          %li
            = link_to "新規登録", new_user_registration_path, class: "post"