config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "events#index"
  resources :users, only: [:show, :edit, :update]
  resources :rooms, only: [:index, :create, :show]
  resources :messages, only: [:create, :destroy]


  resources :events, only: [:index, :show, :new, :create, :destroy] do
    resources :comments, only: [:create, :destroy]
    resource :entries, only: [:create]
  end
  
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true

  has_many :comments, dependent: :destroy
  has_many :entries, dependent: :destroy

  belongs_to :recruiter, class_name: "User", foreign_key: "recruiter_id", optional: true
  belongs_to :applicant, class_name: "User", foreign_key: "applicant_id", optional: true  

  def entried_by?(user)
    entries.where(user_id: user.id).exists?
  end

  validates :eventname, presence: true
  validates :reward, presence: true
  validates :genre, presence: true
  validates :datetime, presence: true
  validates :place, presence: true
  validates :limit, presence: true
  validates :details, presence: true

  validates :images, presence: true
  validates_associated :images
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :move_to_index, except: [:index, :show]
  before_action :authenticate_user!, only: [:show]
  before_action :set_event, only: [:show, :destroy]
  # before_action :set_user, only: [:index]
  before_action :show_all_instans, only: [:show]
  
  def index
    @events = Event.all.order(id: "DESC").includes(:recruiter)
  end

  def show
    @comment = Comment.new
    @comments = @event.comments.includes(:user)
    #新着順で表示
    # @comments = @event.comments.order(created_at: :desc)
    @entry = Entry.new
    # @entries = @event.entry.includes(:user)
    @applicants = Entry.where(event_id: @event.id).all
  end

  def new
    @event = Event.new
    @event.images.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to root_path
      flash.now[:alert] = "イベント作成に成功しました"
    else
      @event.images.new
      render :new
      flash.now[:alert] = "イベント作成に失敗しました"
    end
  end

  def destroy
    @event.destroy
  end


  private
  def event_params
    params.require(:event).permit(:eventname, :reward, :genre, :limit, :place, :datetime, :details, :recruiter_id, images_attributes: [:image, :id]).merge(recruiter_id: current_user.id)
  end

  def set_event
    @event = Event.find(params[:id])
  end

  # def set_user
  #   @user = User.find(params[:id])
  # end

  def show_all_instans
    @recruiter = @event.recruiter
    # @user = @event.user
    # @images = Image.where(event_id: params[:id])
    # @image = @images.first
  end

  def move_to_index
    unless user_signed_in?
      redirect_to action: :index
    end
  end
end

app/views/events/_event.html.haml
.Event
  %h1.name
    = event.eventname
  %ul.important
    %li.reward 報酬：
    = event.reward
    円
    %li.genre 募集ジャンル：
    = event.genre
  %table
    %tr
      %th 
        = image_tag event.images.first.image.url
      %td.detail イメージ図
    %tr
      %th 日時
      %td 
        = event.datetime.strftime("%Y年%m月%d日")
    %tr
      %th 開催場所
      %td 
        = event.place
    %tr
      %th 募集人数
      %td 
        = event.limit

  .Auth-Area
    - if user_signed_in? && current_user.id == event.recruiter_id #ログインしているユーザーIDとイベント作成者のIDが一致しているかどうか
      = link_to "詳細を見る", event_path(event.id), method: :get, class: "show-btn"
      = link_to "イベントを削除する", event_path(event.id), method: :delete, class: "Event-delete"
    - else
      = link_to "詳細を見る", event_path(event.id), method: :get, class: "show-btn"
  
  .Event-host
    .Event-host--name イベント作成者：
    .Event-host--image
      - if event.recruiter.image.url
        = image_tag event.recruiter.image.url, class: "UserImage__icon"
      - else
        = image_tag asset_path("No-image.png"), class: "NoImage__icon"
    %p.recruiter-name
      = event.recruiter.name

    

 

app/views/events/create.html.haml
.CreateBox
  %h1 イベントを作成しました！

  %selection
    = link_to "トップページに戻る", root_path, class: "Totop"

app/views/events/destroy.html.haml
.Event-Deleted
  .success
    %h3 イベントを削除しました。
    = link_to "トップページに戻る", root_path, class: "DeletedEvent"

app/views/events/index.html.haml
.top-content
  .container
    %h1 Unity
    -# %h1 All You Want.
    %p Unityは企業とパフォーマーをつなぐプラットフォームです。
    %p あなたが培ってきたパフォーマンススキルを活かしてみませんか。
    .btn-wrapper
      = link_to "https://www.facebook.com/", class: "btn-wrapper__btn btn-wrapper__btn--facebook" do
        = icon('fab', 'facebook-square',  class: "btn-wrapper__btn--icon")
        %span<>
          Facebook
      = link_to "https://twitter.com/", class: "btn-wrapper__btn btn-wrapper__btn--twitter" do
        = icon('fab', 'twitter', class: "btn-wrapper__btn--icon")
        %span<>
          Twitter

.Main
  .container
    .heading
      %h2 《  イベント一覧  》
    .Events
      - @events.each do |event|
        =render partial: "event", locals: {event: event}
          

app/views/events/new.html.haml
.EventCreateBox
  .InputBox
    %section.info
      %h1.title
        Event Create
    %section.form
      = form_with model: @event, local: true do |f|
        .field
          = f.label :イベント名
          %span（必須）
          = f.text_field :eventname, autofocus: true, autocomplete: "eventname", placeholder: "踊り祭り", maxlength: "30", class: "input"
        
        .EventField
          .FormLabel
            .LavelName
              イベント画像
              %span（必須）
            -# .LavelRequired
            -#   必須
          #ImageBox-1
            %label.img-label{for: "img-file"}
              .Event-num-0#ImageBox__container
                = f.fields_for :images do |image|
                  #Append-js
                    .js-file_group{"data-index" => "#{image.index}"}
                      = image.file_field :image, type: 'file', id:"img-file", class:'js-file', data:{index:"0"}
                %i.fas.fa-camera
      
        .field
          = f.label :報酬額
          %span（必須）
          = f.number_field :reward, autofocus: true, min: 1000, max: 100000, class: "input"
          円
        
        .field
          = f.label :募集カテゴリ
          %span（必須）
          = f.select :genre, [ ["ダンス",1], ["歌", 2], ["撮影モデル", 3] ,["楽器演奏", 4], ["演技", 5], ["サロン・カットモデル", 6], ["エキストラ", 7], ["マジック", 8], ["その他", 9] ], prompt: "募集カテゴリを選択してください", required: true, class: "input"
        
        .field
          = f.label :募集人数
          %span（必須）
          = f.number_field :limit, autofocus: true, min: 1, max: 1000, class: "input"
          人
        
        .field
          = f.label :開催日時
          %span（必須）
          = f.date_select :datetime, {discard: true}
        
        .field
          = f.label :開催場所
          %span（必須）
          = f.text_field :place, autofocus: true, autocomplete: "place", placeholder: "例) 東京国際フォーラム", maxlength: "30", class: "input"

        -# .field
        -#   = f.label :詳細（住所、urlなど）
        -#   %span（必須）
        -#   = f.text_field :place, autofocus: true, autocomplete: "place", placeholder: "", maxlength: "30", class: "input"
          
        .field
          = f.label :イベント詳細説明
          %span（必須）
          = f.text_area :details, autofocus: true, autocomplete: "details", placeholder: "このイベントは・・・", maxlength: "1000", class: "input"

        = f.submit "イベント作成", id: "new-event", class: "NewEventBtn"

app/views/events/show.html.haml
.Event
  %h1.name 
    = @event.eventname
  %ul.important
    %li.reward 報酬：
    = @event.reward
    円
    %li.genre 募集ジャンル：
    = @event.genre
  .Event--image
    = image_tag @event.images.first.image.url
  %table
    -# %tr
    -#   %th 
    -#     = image_tag @event.images.first.image.url
    -#   %td.detail イメージ図
    %tr
      %th 日時
      %td 
        = @event.datetime.strftime("%Y年%m月%d日")
    %tr
      %th 開催場所
      %td 
        = @event.place
    %tr
      %th 募集人数
      %td 
        = @event.limit
  %p.item 【  詳細説明  】
  %p.details 
    = @event.details

  - if @event.recruiter_id == current_user.id
    %h1.EventOwener あなたはイベント作成者です。
  - elsif @event.entries.where(user_id: current_user.id).exists?
    %h1.EventOwener このイベントは申し込み済みです。
  - else
    .Application
      = link_to "申し込む", event_entries_path(@event.id), id: "JoinEvent", class: "ApplicationSubmit", method: :post
      -# = form_with model: [@event, @entry], local: true, class: 'EventApplication' do |f|
        -# = f.text_field :name, placeholder: "name", size: 30, class: "input"
        -# = f.email_field :email, placeholder: "sample@.com", class: "input"
        -# = f.text_field :phoneNumber, placeholder: "XXX-XXXX-XXXX", class: "input"
        -# = icon("fas", "video", class: "video")
        -# = f.label :video do
        -#   = f.file_field :video, :accept => 'video/*', class: "Hidden"
        -# = f.submit "申し込む", class: 'ApplicationSubmit'

  .MainShow__box__comment
    .Title
      コメント一覧
    .MainShow__box__comments#Comments
      - if @comments
        - @comments.each do |comment|
          .MainShow__box__comments__comment
            .Profile
              .Profile__right
                .Image
                  - if comment.user.image?
                    = image_tag comment.user.image.url, class: "user-circle"
                  - else
                    = icon('far', 'smile-wink', class: "user-circle" )
                .Seller_or_buyer
                  = comment.user.name
            .Comment
              .Comment__text
                = comment.content
              .Comment__bottom
                .Comment__date
                  = icon('far', 'clock')
                  = comment.created_at.strftime("%Y年%m月%d日 %H時%M分")
                .Comment__trash
                  = link_to event_comment_path(comment.event.id, comment.id), "event_id": :@event, method: :delete do
                    = icon('fa', 'trash')
    - if current_user
      = form_with model: [@event, @comment], local: true, class: "New_comment", id: "comment_form" do |f|
        = f.text_area :content, required: "required", class: "Text_area", placeholder: "コメントする"
        %p.note
          イベントの疑問点についてコメントをしてみましょう。
          %br 不快な言葉遣いなどは利用制限や退会処分となる場合があります。
        .Send
          = f.submit "コメントする", class: "Comment__btn"
    - else
      %p.note
        イベントへの申込みやコメントの投稿には新規会員登録/ログインが必要です。
  
  %h2 申込者一覧
  
  .Applicant
    - @applicants.each do |applicant|
      .Applicant__Members
        .Applicant__Members--image
          - if applicant.user.image?
            = image_tag applicant.user.image.url, class: "Applicant-image"
          - else  
            = image_tag asset_path("No-image.png"), class: "NoImage__icon"
        .Applicant__Members--name
          = link_to user_path(applicant.user.id), class: "To-applicant" do
            = applicant.user.name