config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "events#index"
  resources :users, only: [:show, :edit, :update]
  resources :rooms, only: [:index, :create, :show]
  resources :messages, only: [:create, :destroy]


  resources :events, only: [:index, :show, :new, :create, :destroy] do
    resources :comments, only: [:create, :destroy]
    resource :entries, only: [:create]
  end
  
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
  has_many :deals
  has_many :users, through: :deals
  
  # def show_last_message
  #   if (last_message = messages.last).present?
  #     if last_message.content?
  #       last_message.content
  #     else
  #       '画像が投稿されています'
  #     end
  #   else
  #     'まだメッセージはありません。'
  #   end
  # end
  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def index
    @currentRooms = current_user.rooms
  end

  def create
    @room = Room.create
    @deal1 = Deal.create(room_id: @room.id, user_id: current_user.id)
    @deal2 = Deal.create(params.require(:deal).permit(:user_id, :room_id).merge(room_id: @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    if Deal.where(user_id: current_user.id,room_id: @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @deals = @room.deals
    else
      redirect_back(fallback_location: root_path)
    end
  end

end

app/views/rooms/index.html.haml
.AllRooms
  - @currentRooms.each do | room |
    = link_to room_path(room.id), class: "To-room" do
      .AllRooms__Room
        .AllRooms__Room--head
          - if room.messages.last.user.image?
            = image_tag room.messages.last.user.image.url, class: "user-circle"
          - else
            = icon('far', 'smile-wink', class: "user-circle" )
          = room.messages.last.user.name
          = room.messages.last.created_at.strftime("%Y-%m-%d %H:%M")
        .AllRooms__Room--body
          = room.messages.last.message

app/views/rooms/show.html.haml
%h4.rooms-title メッセージ

.InputSpace
  - @deals.each do |d|
    .user-name
      = d.user.name
      さん
      
      
  .posts
    = form_for @message do |f|
      = f.text_area :message, required: "required", placeholder: "メッセージを入力して下さい" , size: 100, class:"form-area-field"
      = f.hidden_field :room_id, value: @room.id
      = f.submit "送信する", class: 'form-submit'
    
  .protocol
    %h1 注意事項
    %p.explanation Unityを介さずに行う直接取引、勧誘、宣伝行為を禁止しております。
    %p これらの行為が確認された場合、アカウント制限等の対応をさせていただきますのでご注意ください。


.ChatSpace
  - if @messages.present?
    - @messages.each do |m|
      .chat-box
        .chat-top
          .chat-face
            - if m.user.image?
              = image_tag m.user.image.url, class:"user-circle"
            - else
              = icon('far', 'smile-wink', class: "user-circle" )
          .chat-name
            = m.user.name
          .chat-date
            = m.created_at.strftime("%Y-%m-%d %H:%M")
            = link_to "削除", message_path(m.id), method: :delete, class: "Message-delete"
        .chat-content
          = m.message